## Load the Cleaned Dataset

In [11]:
import pandas as pd
df = pd.read_csv(
    "../data/processed/cleaned_demand_timeseries.csv",
    parse_dates = [0],
    index_col = 0
)

df.head()

                     demand  demand_diff
timestamp
2023-01-01 00:00:00   18995          NaN
2023-01-01 00:30:00   19730        735.0
2023-01-01 01:00:00   19327       -403.0
2023-01-01 01:30:00   18589       -738.0
2023-01-01 02:00:00   17806       -783.0

## Creat Lag features

In [12]:
# Previous half hour
df["lag_1"] = df["demand"].shift(1)

# Same time previous day
df["lag_48"] = df["demand"].shift(48)

df[["demand", "lag_1", "lag_48"]].head(60)

                     demand    lag_1   lag_48
timestamp
2023-01-01 00:00:00   18995      NaN      NaN
2023-01-01 00:30:00   19730  18995.0      NaN
2023-01-01 01:00:00   19327  19730.0      NaN
2023-01-01 01:30:00   18589  19327.0      NaN
2023-01-01 02:00:00   17806  18589.0      NaN
2023-01-01 02:30:00   17105  17806.0      NaN
2023-01-01 03:00:00   16459  17105.0      NaN
2023-01-01 03:30:00   15691  16459.0      NaN
2023-01-01 04:00:00   15221  15691.0      NaN
2023-01-01 04:30:00   14936  15221.0      NaN
2023-01-01 05:00:00   14910  14936.0      NaN
2023-01-01 05:30:00   15034  14910.0      NaN
2023-01-01 06:00:00   15545  15034.0      NaN
2023-01-01 06:30:00   15894  15545.0      NaN
2023-01-01 07:00:00   16449  15894.0      NaN
2023-01-01 07:30:00   16805  16449.0      NaN
2023-01-01 08:00:00   17346  16805.0      NaN
2023-01-01 08:30:00   18152  17346.0      NaN
2023-01-01 09:00:00   19046  18152.0      NaN
2023-01-01 09:30:00   19671  19046.0      NaN
2023-01-01 10:00:00   20476  19671.0      NaN
2023-01-01 10:30:00   21122  20476.0      NaN
2023-01-01 11:00:00   21847  21122.0      NaN
2023-01-01 11:30:00   22660  21847.0      NaN
2023-01-01 12:00:00   23654  22660.0      NaN
2023-01-01 12:30:00   24203  23654.0      NaN
2023-01-01 13:00:00   24417  24203.0      NaN
2023-01-01 13:30:00   24548  24417.0      NaN
2023-01-01 14:00:00   24760  24548.0      NaN
2023-01-01 14:30:00   25232  24760.0      NaN
2023-01-01 15:00:00   25684  25232.0      NaN
2023-01-01 15:30:00   26320  25684.0      NaN
2023-01-01 16:00:00   27525  26320.0      NaN
2023-01-01 16:30:00   28510  27525.0      NaN
2023-01-01 17:00:00   29230  28510.0      NaN
2023-01-01 17:30:00   29154  29230.0      NaN
2023-01-01 18:00:00   28532  29154.0      NaN
2023-01-01 18:30:00   27976  28532.0      NaN
2023-01-01 19:00:00   27370  27976.0      NaN
2023-01-01 19:30:00   26233  27370.0      NaN
2023-01-01 20:00:00   25700  26233.0      NaN
2023-01-01 20:30:00   25414  25700.0      NaN
2023-01-01 21:00:00   24521  25414.0      NaN
2023-01-01 21:30:00   23496  24521.0      NaN
2023-01-01 22:00:00   22721  23496.0      NaN
2023-01-01 22:30:00   21736  22721.0      NaN
2023-01-01 23:00:00   20585  21736.0      NaN
2023-01-01 23:30:00   19733  20585.0      NaN
2023-01-02 00:00:00   21550  19733.0  18995.0
2023-01-02 00:30:00   22238  21550.0  19730.0
2023-01-02 01:00:00   21894  22238.0  19327.0
2023-01-02 01:30:00   21459  21894.0  18589.0
2023-01-02 02:00:00   20926  21459.0  17806.0
2023-01-02 02:30:00   20675  20926.0  17105.0
2023-01-02 03:00:00   20287  20675.0  16459.0
2023-01-02 03:30:00   19938  20287.0  15691.0
2023-01-02 04:00:00   19826  19938.0  15221.0
2023-01-02 04:30:00   19724  19826.0  14936.0
2023-01-02 05:00:00   20320  19724.0  14910.0
2023-01-02 05:30:00   21268  20320.0  15034.0

## Create Rolling Statistics

In [13]:
# Rolling mean (daily window)
df["rolling_mean_48"] = df["demand"].rolling(window=48).mean()

df[["demand", "rolling_mean_48"]].head(100)

                     demand  rolling_mean_48
timestamp
2023-01-01 00:00:00   18995              NaN
2023-01-01 00:30:00   19730              NaN
2023-01-01 01:00:00   19327              NaN
2023-01-01 01:30:00   18589              NaN
2023-01-01 02:00:00   17806              NaN
...                     ...              ...
2023-01-02 23:30:00   21625     28047.125000
2023-01-03 00:00:00   22500     28066.916667
2023-01-03 00:30:00   23043     28083.687500
2023-01-03 01:00:00   22636     28099.145833
2023-01-03 01:30:00   22136     28113.250000

[100 rows x 2 columns]

## Extract Date & Time Components

In [14]:
# Critical features for XGBoost and LSTM
dt_idx = pd.DatetimeIndex(df.index)

df["hour"] = dt_idx.hour
df["day_of_week"] = dt_idx.dayofweek
df["month"] = dt_idx.month

df[["hour", "day_of_week", "month"]].head()

                     hour  day_of_week  month
timestamp
2023-01-01 00:00:00     0            6      1
2023-01-01 00:30:00     0            6      1
2023-01-01 01:00:00     1            6      1
2023-01-01 01:30:00     1            6      1
2023-01-01 02:00:00     2            6      1

## Drop rows with NaNs (Created by Lags)

In [15]:
df_fe = df.dropna()

df_fe.isna().sum()

demand             0
demand_diff        0
lag_1              0
lag_48             0
rolling_mean_48    0
hour               0
day_of_week        0
month              0
dtype: int64

## Save Feature-Engineered Dataset

In [16]:
# Save the fULL dataset (Unscaled, No Split)
# This file will be the input for BOTH XGBoost and LSTM later.
df_fe.to_csv("../data/processed/feature_engineered_unscaled.csv")

print("Feature engineering complete. File saved to: ../data/processed/feature_engineered_unscaled.csv")
print(f"Shape: {df_fe.shape}")

Feature engineering complete. File saved to: ../data/processed/feature_engineered_unscaled.csv
Shape: (282096, 8)